---
name: ddu-source-chronicle
description: ddu.vim source for yukimemi/dps-chronicle
---

=pod

=head1 ddu-source-chronicle

ddu-source-chronicle is a ddu source for L<yukimemi/dps-chronicle|https://github.com/yukimemi/dps-chronicle>.

=head1 Requirements X<ddu-source-chronicle-requirements>

=item [Deno - A modern runtime for JavaScript and TypeScript](https://deno.land/)

=item [vim-denops/denops.vim: 🐜 An ecosystem of Vim/Neovim which allows developers to write cross-platform plugins in Deno](https://github.com/vim-denops/denops.vim)

=item [Shougo/ddu.vim: Dark deno-powered UI framework for neovim/Vim8](https://github.com/Shougo/ddu.vim)

=item [Shougo/ddu-kind-file: File kind for ddu.vim](https://github.com/Shougo/ddu-kind-file)

=item [yukimemi/dps-chronicle: Denops Chronicle](https://github.com/yukimemi/dps-chronicle)

=head1 Usage X<ddu-source-chronicle-usage>

=begin vim

  " default
  call ddu#start({"sources": [{"name": "chronicle"}]})

  " kind specific
  call ddu#start({"sources": [{"name": "chronicle", "params": {"kind": "write"}}]})

=end vim

=head1 Params X<ddu-source-chronicle-params>

C<ddu-source-chronicle-param-kind>            X<ddu-source-chronicle-param-kind>
source kind of L<dps-chronicle>
Default is "read"
["read", "write"]

=head1 License X<ddu-source-chronicle-license>

Licensed under MIT License.

Copyright (c) 2023 yukimemi

=cut
